from setuptools import setup, find_packages

setup(
    name="clinical-doc-nlp-analyzer",
    version="0.1.0",
    author="Michael Kwakye Agyapong",
    author_email="mkwakyeagyapong@gmail.com",
    description="Open-access NLP toolkit for detecting clinical documentation deficiencies in EHR systems",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/mkagyapong/clinical-doc-nlp-analyzer",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "nltk>=3.8.1",
        "spacy>=3.7.0",
        "scikit-learn>=1.3.0",
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "pyyaml>=6.0",
        "jinja2>=3.1.0",
        "python-dateutil>=2.8.0",
        "regex>=2023.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Healthcare Industry",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
    ],
    keywords="nlp clinical-documentation ehr healthcare patient-safety long-term-care",
)
